### ISSUE TITLE
/go/ plugin

### ISSUE THREAD

**Issue by szepeviktor** [Yoast/archive#2]
Hello @omarreiss !
Is your "redirection-counter"/click-through plugin open-source?

Thank you.

**Comment by omarreiss** [comment]
Hi @szepeviktor I am not sure what you mean, but everything in this repo is open source.

**Comment by omarreiss** [comment]
I think you mean https://yoast.com/cloak-affiliate-links/. You can download the PHP script there.

**Comment by szepeviktor** [comment]
Thank you for the link.
I would implement it with WordPress Rewrite API.
